name: Test Python SDK

on:
  workflow_call:
    secrets:
      NVM_API_KEY:
        required: true
        description: 'NanoVM API key for testing'

jobs:
  integration_tests:
    runs-on: ubuntu-24.04
    permissions:
      contents: read
      id-token: write
    defaults:
      run:
        working-directory: ./packages/python-sdk
    name: Build and test SDK
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      - name: Install and configure Poetry
        uses: snok/install-poetry@v1
        with:
          version: 1.5.1
          virtualenvs-create: true
          virtualenvs-in-project: true
          installer-parallel: true

      - name: Install dependencies
        run: poetry install

      - name: Test build
        run: poetry build

      - name: Run tests
        run: poetry run pytest --verbose -x
        env:
          NVM_API_KEY: ${{ secrets.NVM_API_KEY }}
