name: Build and push Desktop template

on:
  push:
    paths:
      - "template/**"
      - ".github/workflows/template.yml"
    branches:
      - main

permissions:
  contents: read

jobs:
  buildAndPublish:
    defaults:
      run:
        working-directory: ./template

    name: Build and Push Images
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to DockerHub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push to DockerHub
        run: |
          docker pull ${{ secrets.DOCKERHUB_USERNAME }}/desktop:latest || true
          docker buildx build \
            --file Dockerfile \
            --platform linux/amd64 \
            --push \
            --tag ${{ secrets.DOCKERHUB_USERNAME }}/desktop:latest .

      - name: Install NanoVM CLI
        run: npm install -g @nanovm/cli

      - name: Build nanovm
        run: nanovm template build
        env:
          NVM_ACCESS_TOKEN: ${{ secrets.NVM_ACCESS_TOKEN }}
